src/Entity/Profile.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 */
class Profile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $gender;

    /**
     * @ORM\Column(type="text",  nullable=true)
     */
    private $about_me;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     */
    private $id_user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAboutMe(): ?string
    {
        return $this->about_me;
    }

    public function setAboutMe(?string $about_me): self
    {
        $this->about_me = $about_me;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }
}

templates/profile_id/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileEditController!{% endblock %}

{% block body %}


    {% for user in user1 %}
        <div class="nav-item">
        <ul class="navbar-nav">
            <h4>Имя</h4>
            <li>
                <p>{{ user.name }} </p>
            </li>
            <h4>Email</h4>
            <li>
                <p>{{ user.idUser }}</p>
            </li>
            <h4>Пол</h4>
            <li>
                <p>{{ user.gender }} </p>
            </li>
            <h4>О себе</h4>
            <li>
                <p>{{ user.aboutMe }} </p>
            </li>
        </ul>
        </div>
    {% endfor %}


{% endblock %}